import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Prodcts",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<main>{children}</main>)
}
